"""harness — invoke AI coding-agent CLIs uniformly.

Public API:
    from harness import run, run_async, build_command, parse_output, RunSpec, RunResult, BuildCommand, list_adapters

Importing this package registers every shipped adapter.
"""
from harness.base import (
    Adapter,
    AgentStatus,
    AmpOptions,
    Backend,
    BuildCommand,
    Capabilities,
    ClaudeCodeOptions,
    ClineOptions,
    CodexOptions,
    CopilotOptions,
    ErrorCode,
    GracefulSignal,
    HarnessError,
    InstallMeta,
    KiroOptions,
    NativeOptions,
    OutputCallback,
    OutputStream,
    ParsedOutput,
    PermissionPolicy,
    QoderOptions,
    QoderPermissionMode,
    ReadyState,
    RunResult,
    RunSpec,
    ScrollKeys,
    SessionTelemetry,
    Termination,
    TimeoutKind,
    VibeOptions,
)
from harness.pricing import ModelPricing, derive_cost, lookup_pricing
from harness.registry import (
    build_command,
    get_adapter,
    get_capabilities,
    list_adapters,
    parse_output,
    register,
    run,
    run_async,
)
from harness._instructions import (
    InstructionProjection,
    PreparedCommand,
    cleanup_command,
    prepare_command,
    project_instructions,
    restore_projected_instructions,
    write_instructions,
)
from harness._subproc import SubprocOutcome, run_subprocess, run_subprocess_async
from harness.sessions import (
    AmpEffort,
    AmpSdkOptions,
    AmpVisibility,
    LiveSession,
    OmpSdkOptions,
    OpenCodeApprovalResponse,
    OpenCodeAuth,
    OpenCodeOptions,
    SessionCapabilities,
    SessionEvent,
    SessionReference,
    SessionSpec,
    SessionTurn,
    SessionTurnResult,
    SessionTurnStatus,
    get_session_capabilities,
    open_session,
)
from harness.util import last_lines, last_non_empty_join, strip_ansi

import harness.adapters  # noqa: E402,F401 — registers the shipped adapters

__all__ = [
    "Adapter",
    "AgentStatus",
    "AmpEffort",
    "AmpOptions",
    "AmpSdkOptions",
    "AmpVisibility",
    "Backend",
    "BuildCommand",
    "Capabilities",
    "ClaudeCodeOptions",
    "ClineOptions",
    "CodexOptions",
    "CopilotOptions",
    "ErrorCode",
    "GracefulSignal",
    "HarnessError",
    "InstallMeta",
    "InstructionProjection",
    "KiroOptions",
    "LiveSession",
    "ModelPricing",
    "NativeOptions",
    "OmpSdkOptions",
    "OpenCodeApprovalResponse",
    "OpenCodeAuth",
    "OpenCodeOptions",
    "OutputCallback",
    "OutputStream",
    "ParsedOutput",
    "PermissionPolicy",
    "PreparedCommand",
    "QoderOptions",
    "QoderPermissionMode",
    "ReadyState",
    "RunResult",
    "RunSpec",
    "ScrollKeys",
    "SessionCapabilities",
    "SessionEvent",
    "SessionReference",
    "SessionSpec",
    "SessionTelemetry",
    "SessionTurn",
    "SessionTurnResult",
    "SessionTurnStatus",
    "SubprocOutcome",
    "Termination",
    "TimeoutKind",
    "VibeOptions",
    "build_command",
    "cleanup_command",
    "derive_cost",
    "get_adapter",
    "get_capabilities",
    "get_session_capabilities",
    "last_lines",
    "last_non_empty_join",
    "list_adapters",
    "lookup_pricing",
    "open_session",
    "parse_output",
    "prepare_command",
    "project_instructions",
    "register",
    "restore_projected_instructions",
    "run",
    "run_async",
    "run_subprocess",
    "run_subprocess_async",
    "strip_ansi",
    "write_instructions",
]
__version__ = "0.3.17"
